apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: app1
  source:
    path: "HelmCharts/MyChart1"
    repoURL: "git@github.com:DimitryZH/argo-cd-app.git"
    targetRevision: HEAD
    helm:
      valueFiles:
        - values_prod.yaml
      parameters:
        - name: "container.image"
          value: dmitryzhuravlev/testapp:v1

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
